// All products data - matches schema.ts structure
export const allProducts = [
  {
    id: 1,
    name: "SOS TOP Movies",
    slug: "sos-top-movies",
    tagline: "Learn to build modern full stack applications with Next.js",
    description: "A Movie Recommendation App",
    websiteUrl: "https://sos-top-movies-project-react.vercel.app/",
    tags: ["React.JS", "Movies", "Global"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "mohislamedu@gmail.com",
    voteCount: 120,
  },
  {
    id: 2,
    name: "SOS Amazon",
    slug: "sos-amazon",
    tagline: "Find any Product you might look for",
    description: "A Simple Amazon App",
    websiteUrl: "https://sos-amazon-training.vercel.app/",
    tags: ["B2B", "SaaS"],
    createdAt: new Date("2024-01-18"),
    approvedAt: new Date("2024-01-19"),
    status: "approved" as const,
    submittedBy: "mohislamedu@gmail.com",
    voteCount: 87,
  },
  {
    id: 3,
    name: "SOS Desserts",
    slug: "sos-desserts",
    tagline: "Explore beautiful desserts",
    description: "A Simple Desserts Store",
    websiteUrl: "https://simple-dessert-store-cart.vercel.app/",
    tags: ["Desserts", "Marketing"],
    createdAt: new Date("2024-01-20"),
    approvedAt: new Date("2024-01-21"),
    status: "approved" as const,
    submittedBy: "mohislamedu@gmail.com",
    voteCount: 56,
  },
  {
    id: 4,
    name: "SOS Weathering",
    slug: "sos-weathering",
    tagline: "A Quick Guide to Forecast",
    description: "A Simple Forecast App",
    websiteUrl: "https://simple-weather-app-one-rho.vercel.app/",
    tags: ["Forecast", "SaaS", "Conversion"],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: "pending" as const,
    submittedBy: "mohislamedu@gmail.com",
    voteCount: 61,
  },
  {
    id: 5,
    name: "SOS Grad Project",
    slug: "sos-grad-project",
    tagline: "Air Quality Monitoring & Control",
    description: "BUC'21 Graduation Website",
    websiteUrl: "https://buc21-gradproject-aqmc.vercel.app/",
    tags: ["SaaS", "Weather", "Global"],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000), // 4 days ago
    approvedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "mohislamedu@gmail.com",
    voteCount: 612,
  },
];
